# Generated by Django 2.2.16 on 2020-10-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hoper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.CharField(max_length=15, verbose_name='ビジョン')),
                ('vision_content', models.TextField(verbose_name='ビジョン文章')),
                ('feature', models.CharField(max_length=15, verbose_name='特徴')),
                ('feature_content', models.TextField(verbose_name='特徴文章')),
                ('student', models.CharField(max_length=15, verbose_name='生徒')),
                ('student_content', models.TextField(verbose_name='生徒文章')),
                ('action', models.CharField(max_length=15, verbose_name='活動報告')),
                ('action_content', models.TextField(verbose_name='活動報告文章')),
                ('join', models.CharField(max_length=15, verbose_name='入会')),
                ('join_content', models.TextField(verbose_name='入会文章')),
            ],
        ),
    ]
