# Generated by Django 2.2.16 on 2020-10-18 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoper',
            name='action',
        ),
        migrations.RemoveField(
            model_name='hoper',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='hoper',
            name='join',
        ),
        migrations.RemoveField(
            model_name='hoper',
            name='student',
        ),
        migrations.RemoveField(
            model_name='hoper',
            name='vision',
        ),
    ]
