# Generated by Django 2.2.16 on 2020-10-24 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201019_0642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hoper',
            new_name='About',
        ),
    ]
