# Generated by Django 2.2.16 on 2021-01-09 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201024_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50, verbose_name='ブラン名')),
                ('plan_explanation', models.TextField(verbose_name='プラン説明')),
                ('plan_price', models.IntegerField(default=0, verbose_name='プラン価格')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='質問カテゴリ')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('think', models.TextField(verbose_name='思い')),
                ('history', models.TextField(verbose_name='経歴')),
                ('profile', models.TextField(verbose_name='プロフィール')),
                ('private', models.TextField(verbose_name='プライベート')),
            ],
        ),
        migrations.CreateModel(
            name='TopMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='First View 文章 ')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='質問内容')),
                ('answer', models.TextField(verbose_name='回答')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QuestionCategory')),
            ],
        ),
        migrations.CreateModel(
            name='PlanContentsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='プラン内容')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Plan')),
            ],
        ),
    ]
