# Generated by Django 2.2.16 on 2021-01-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_plan_plancontentscategory_question_questioncategory_teacher_topmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='plan_explanation',
            new_name='explanation',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='plan_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='plan',
            old_name='plan_price',
            new_name='price',
        ),
    ]
